apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: $MICRO_SERVICE
  name: $MICRO_SERVICE
spec:
  replicas: $REPLICAS
  selector:
    matchLabels:
      app: $MICRO_SERVICE
  template:
    metadata:
      labels:
        app: $MICRO_SERVICE
    spec:
      imagePullSecrets:
      - name: $SECRET_NAME
      containers:
      - image: $IMAGE_NAME:$IMAGE_TAG
        name: $MICRO_SERVICE
        ports:
          - containerPort: $CONTAINER_PORT

  
        volumeMounts:
          - name: config-map
            mountPath: "/app/.env"
            subPath: .env
            readOnly: true

          - mountPath: "/app/data/downloaded"
            name: pvc


      volumes:
      - name: config-map
        configMap:
          name: env-file

      - name: pvc
        persistentVolumeClaim:
          claimName: storage-pvc
      restartPolicy: Always
